---
skip_compilation: true

verification:
  files_must_exist:
    # Standard IOC boot files (created by deploy_ioc)
    - iocBoot/st.cmd
    - iocBoot/epicsEnv.cmd
    - iocBoot/postInit.cmd
    # Role-specific files
    - iocBoot/base.cmd
    - db/motornanofaktur.substitutions

  file_must_contain:
    iocBoot/st.cmd:
      - "iocInit"
    iocBoot/base.cmd:
      - "dbLoadDatabase"
      - "registerRecordDeviceDriver"
      - 'dbLoadRecords("$(MOTOR)/db/motorUtil.db", "P=$(P)")'
      - "drvAsynIPPortConfigure"
      - "nFSystemCreateController"
      - 'dbLoadTemplate("$(TOP)/db/motornanofaktur.substitutions")'

  file_must_not_contain:
    iocBoot/st.cmd:
      - "{{"  # No unrendered jinja
      - "}}"
    iocBoot/base.cmd:
      - "{{"
      - "}}"
    iocBoot/epicsEnv.cmd:
      - "{{"
      - "}}"

  permissions:
    iocBoot/st.cmd: "0775"
